### ISSUE TITLE
Part 2 seems to be in Chinese (I think)

### ISSUE THREAD

**Issue by rainkinz** [makotogo/HelloJUnit5#2]
I've tried opening this in a few different browsers, but it keeps coming up as what looks like Chinese I think:

https://www.ibm.com/developerworks/library/j-introducing-junit5-part2-vintage-jupiter-extension-model/index.html

Trying to change the language in the menu at the footer, doesn't do anything.

**Comment by makotogo** [comment]
This is an issue with IBM developerWorks, not with this repository.

I will contact IBM developerWorks and report the problem.

**Comment by rainkinz** [comment]
Thank you, and thank you for the tutorial.
